### ISSUE TITLE
conflicting licenses in the repo

### ISSUE THREAD

**Issue by romerocesar** [jhuapl-bio/taxtriage#62]
### Description of feature

The [LICENSE](https://github.com/jhuapl-bio/taxtriage/blob/main/LICENSE) has an unresolved merge conflict and shows two open source licenses (i.e. MIT and GPLv3). While these licenses are largely compatible, GPLv3 is more restrictive than MIT and the ambiguity may affect projects interested in leveraging workflows in this repo.

Upon inspecting the history, it seems the original intention was to replace [GPL with MIT](https://github.com/jhuapl-bio/taxtriage/commit/db77be0e634b55c5f29babed4307e863a29b0aab#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) and later accidentally [the conflict was introduced](https://github.com/jhuapl-bio/taxtriage/commit/c99627ec47f8367a111b4f23dad7df6cbdf886f0) without being resolved.

Can you confirm which license is the correct one? I'd happily send a pull request with the change if that helps

**Comment by Merritt-Brian** [comment]
@romerocesar Thanks for catching that conflict. The issue was resolved back to MIT
